# Copyright (c) 2024 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

################################################################################

includes:
#- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
#- ./tk-multi-screeningroom.yml
#- ./tk-multi-shotgunpanel.yml
#- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml
- ./tk-mari-project-manager.yml
################################################################################

# asset
settings.mari.asset:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.mari"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-mari.location"
  
# asset_step
settings.mari.asset_step:
  apps:
    tk-multi-loader2: "@apps.tk-multi-loader2"
    tk-multi-publish2: "@apps.tk-multi-publish2"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.mari"
    tk-mari-projectmanager: "@settings.tk-mari-projectmanager"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-loader2, name: Load}
  - {app_instance: tk-multi-publish2, name: Publish...}
  location: "@engines.tk-mari.location"

# project  
mari.project:
  apps:
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.mari"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-mari.location"
