# ---- Mari

settings.tk-multi-workfiles2.mari:
  show_change_context: true
  show_file_open: false
  show_file_save: false
  my_tasks_filters:
   - [entity, type_is, Asset]
   - [task_assignees, is, '{context.user}']
  entities:
  - caption: Assets
    entity_type: Asset
    hierarchy: [sg_asset_type, code]
    filters:
    sub_hierarchy:
      entity_type: Task
      filters:
      link_field: entity
      hierarchy: [step]
  location: "@apps.tk-multi-workfiles2.location"
